// <auto-generated />
namespace ServiceStatusApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Dodaniewłaściwościuseriddomodeluhistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dodaniewłaściwościuseriddomodeluhistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201709300717226_Dodanie właściwości userid do modelu history"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
