// <auto-generated />
namespace ServiceStatusApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DodaniewłaściwościCompleteDatedoservicehistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DodaniewłaściwościCompleteDatedoservicehistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201709281847455_Dodanie właściwości CompleteDate do servicehistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
